package model.ventas.entities.am.common;

import java.util.ArrayList;

import java.util.Map;

import model.ventas.entities.vo.clases.TablaDinamicaVOBean;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 25 19:39:50 CDT 2021
// ---------------------------------------------------------------------
public interface VentasAM extends ApplicationModule {
    
    void imprimirProductos();

    void incrementarPrecio(double porcentaje);

    void filtrarCLiente(String p_nombre);


    Map<String, TablaDinamicaVOBean> execute(String p_nombreTabla, Integer p_idTareaBpm);

    String invocarVoJarProgramatico(String data, int num);
}

