package model.ventas.entities.vo;

import java.util.ArrayList;
import java.util.Collection;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import model.ventas.entities.vo.clases.TablaDinamicaVOBean;

import model.ventas.entities.vo.clases.TablaDinamicaWebServicesClientImpl;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 29 12:42:43 CDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TablaDinamicaVOImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TablaDinamicaVOImpl() {
    }

    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {
        Collection<Object> value = super.getScrollableData(filter);
        return value;
    }
    
    public ArrayList<String> test(String mess){
        System.out.println("Mensaje impreso desde el VO Programatico " + mess);
        
        // Declaración de un ArrayList de "String". Puede ser de cualquier otro Elemento u Objeto (float, Boolean, Object, ...)
        ArrayList<String> nombreArrayList = new ArrayList<String>();
        // Añade el elemento al ArrayList
        nombreArrayList.add(mess);
        nombreArrayList.add("Elemento 2");
        
        return nombreArrayList;
    }
    
    
    public String validaJarImplement(String s, int i){
        TablaDinamicaWebServicesClientImpl instance = new  TablaDinamicaWebServicesClientImpl();
        String vo =  instance.invocaJar(s, i);
        return "Mensaje desde VO";    
    }
    
    
    public Map<String,TablaDinamicaVOBean> validacionDinamica(String p_nombreTabla, Integer p_idTareaBpm){
        
        String message;
        System.out.println("========================================");
        System.out.println("-- INVOCACION WEB SERVICES ");
        System.out.println("==========================================");
        
        // Declaración de un Mapa de "String". Puede ser de cualquier otro Elemento u Objeto (float, Boolean, Object, ...)
        Map<String,TablaDinamicaVOBean> map = new HashMap <String,TablaDinamicaVOBean>();
        TablaDinamicaWebServicesClientImpl instance = new  TablaDinamicaWebServicesClientImpl();
        map = instance.invocarWebServcices(p_nombreTabla, p_idTareaBpm);
        
        message = validaEjecucion(map);
        
        System.out.println("========================================");
        System.out.println("-- PROCESO " + message);
        System.out.println("==========================================");
        
        
        
        return map;
    }
    
    private String validaEjecucion(Map<String,TablaDinamicaVOBean> map){
        String mess = "";
        
        if( map.size() == 1 ){
            Iterator it = map.keySet().iterator();
            while(it.hasNext()){
              String key = it.next().toString();
              System.out.println("Clave: " + key + " -> Valor: " + map.get(key));
                mess= key;
            }
            
        }
        else{
            mess= "Invocación Exítosa";
        }
        
        return mess;
        }
    
    
    
}

